### ISSUE TITLE
Image dissapearing issue still here on latest version

### ISSUE THREAD

**Issue by ProGitHubUser** [StylexTV/GSigns#15]
Somehow the problem is still here. Same thing as before.

**Comment by stylextv** [comment]
Wdym? There were multiple issues that I fixed.
What exact issue do you have?
A bit more information pls.

**Comment by stylextv** [comment]
Type "/gs update" and try if the issue still exists.

**Comment by ProGitHubUser** [comment]
Alright so I tried /gs update even though I downloaded the latest version from Songoda and it seemed to work. But when I made a sign it didnt work at all and gave me this error: 
[12:15:08 WARN]: [GSigns] Plugin GSigns v5.8 generated an exception while executing task 316
java.lang.IllegalStateException: Asynchronous getNearbyEntities!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1262) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1252) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.CraftWorld.getNearbyEntities(CraftWorld.java:1243) ~[patched_1.16.1.jar:git-Paper-135]
        at de.stylextv.gs.world.BetterFrame.refreshEntityId(BetterFrame.java:169) ~[?:?]
        at de.stylextv.gs.world.BetterFrame.update(BetterFrame.java:102) ~[?:?]
        at de.stylextv.gs.world.WorldUtil$2.run(WorldUtil.java:124) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-135]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-135]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

The issue was the signs were vanishing whenever the server restarted or the chunk unloaded. Now they aren't being made at all. 
Here is an image: 
![image](https://user-images.githubusercontent.com/40724602/96349061-c0afe080-1072-11eb-92c3-e4177f5c1ebe.png)

PaperSpigot 1.16.1

**Comment by stylextv** [comment]
Oh ok I see. While attempting to fix your issues I must have created another issue lol. I am working on it rn

**Comment by ProGitHubUser** [comment]
Alright thanks lol

**Comment by stylextv** [comment]
Hit /gs update and try again please :D

**Comment by stylextv** [comment]
Oh and btw, please update your server to the newest version :)
1.16.1 -> 1.16.3

**Comment by ProGitHubUser** [comment]
It's fixed :) Also I don't have it on 16.3 cause some stuff isn't working on it as of yet

**Comment by stylextv** [comment]
You mean like the last issue you send in is fixed or everything?

**Comment by ProGitHubUser** [comment]
Yeah it all seems to be working

**Comment by stylextv** [comment]
nice :D
