### ISSUE TITLE
Error when server restarts. No image is loaded.

### ISSUE THREAD

**Issue by ghost** [StylexTV/GSigns#6]
Im runing Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
And the latest version of GS 4.3

When the server restarts, spams a huge error, I think 1 per each Item-Frame and no image is loaded. If I remove the gs items and create them again, it works fine. But if the server restarts, it happens again.

I only copied 3 errors as they are all the same but hundred of times.
This is when the server loads the plugin.
```
[15:18:24] [Server thread/WARN]: java.lang.IllegalArgumentException
[15:18:24] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
[15:18:24] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:18:24] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:18:24] [Server thread/WARN]: 	at de.stylextv.gs.world.BetterFrame112.<init>(BetterFrame112.java:128)
[15:18:24] [Server thread/WARN]: 	at de.stylextv.gs.world.WorldUtil.loadFrame(WorldUtil.java:253)
[15:18:24] [Server thread/WARN]: 	at de.stylextv.gs.world.WorldUtil.access$1(WorldUtil.java:146)
[15:18:24] [Server thread/WARN]: 	at de.stylextv.gs.world.WorldUtil$1.run(WorldUtil.java:79)
[15:18:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[15:18:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[15:18:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[15:18:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[15:18:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[15:18:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[15:18:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:18:24] [Server thread/WARN]: java.lang.IllegalArgumentException
[15:18:24] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
[15:18:24] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:18:24] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:18:24] [Server thread/WARN]: 	at de.stylextv.gs.world.BetterFrame112.<init>(BetterFrame112.java:128)
[15:18:24] [Server thread/WARN]: 	at de.stylextv.gs.world.WorldUtil.loadFrame(WorldUtil.java:253)
[15:18:24] [Server thread/WARN]: 	at de.stylextv.gs.world.WorldUtil.access$1(WorldUtil.java:146)
[15:18:24] [Server thread/WARN]: 	at de.stylextv.gs.world.WorldUtil$1.run(WorldUtil.java:79)
[15:18:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[15:18:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[15:18:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[15:18:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[15:18:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[15:18:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[15:18:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[15:18:24] [Server thread/WARN]: java.lang.IllegalArgumentException
[15:18:24] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
[15:18:24] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:18:24] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:18:24] [Server thread/WARN]: 	at de.stylextv.gs.world.BetterFrame112.<init>(BetterFrame112.java:128)
[15:18:24] [Server thread/WARN]: 	at de.stylextv.gs.world.WorldUtil.loadFrame(WorldUtil.java:253)
[15:18:24] [Server thread/WARN]: 	at de.stylextv.gs.world.WorldUtil.access$1(WorldUtil.java:146)
[15:18:24] [Server thread/WARN]: 	at de.stylextv.gs.world.WorldUtil$1.run(WorldUtil.java:79)
[15:18:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[15:18:24] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[15:18:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[15:18:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[15:18:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[15:18:24] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[15:18:24] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

This is after the server loads the plugin and works.
```
[15:18:48] [Craft Scheduler Thread - 17/WARN]: [GamemodeSigns] Plugin GamemodeSigns v4.3 generated an exception while executing task 11009
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.sendMap(CraftPlayer.java:589) ~[patched_1.12.2.jar:git-Paper-1618]
	at de.stylextv.gs.world.BetterFrame112$1.run(BetterFrame112.java:224) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[15:18:48] [Craft Scheduler Thread - 37/WARN]: [GamemodeSigns] Plugin GamemodeSigns v4.3 generated an exception while executing task 11010
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.sendMap(CraftPlayer.java:589) ~[patched_1.12.2.jar:git-Paper-1618]
	at de.stylextv.gs.world.BetterFrame112$1.run(BetterFrame112.java:224) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[15:18:48] [Craft Scheduler Thread - 37/WARN]: [GamemodeSigns] Plugin GamemodeSigns v4.3 generated an exception while executing task 11011
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.sendMap(CraftPlayer.java:589) ~[patched_1.12.2.jar:git-Paper-1618]
	at de.stylextv.gs.world.BetterFrame112$1.run(BetterFrame112.java:224) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by stylextv** [comment]
Thank you for the report.
I am working on it right now.

**Comment by stylextv** [comment]
Fixed, new update will come out in a few minutes

**Comment by stylextv** [comment]
Oh and please consider updating your review (stars) on the spigot site accordingly 😄

**Comment by ghost** [comment]
Hi! Thx. Nice work. I've already rated the new version. Working amazing so far.

**Comment by stylextv** [comment]
Ty, I'm very glad to hear that!
