### ISSUE TITLE
Issue on restart

### ISSUE THREAD

**Issue by zPirroZ3007** [StylexTV/GSigns#8]
```
java.lang.ExceptionInInitializerError: null
	at de.stylextv.gs.packet.PacketListener.start(PacketListener.java:22) ~[?:?]
	at de.stylextv.gs.world.WorldUtil.onEnable(WorldUtil.java:74) ~[?:?]
	at de.stylextv.gs.main.Main.onEnable(Main.java:39) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[TecnoSpigot-Roleplay.jar:git-YAPFA-"b5bded9"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[TecnoSpigot-Roleplay.jar:git-YAPFA-"b5bded9"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[TecnoSpigot-Roleplay.jar:git-YAPFA-"b5bded9"]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[?:?]
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[?:?]
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[TecnoSpigot-Roleplay.jar:git-YAPFA-"b5bded9"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[TecnoSpigot-Roleplay.jar:git-YAPFA-"b5bded9"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[TecnoSpigot-Roleplay.jar:git-YAPFA-"b5bded9"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:723) ~[TecnoSpigot-Roleplay.jar:git-YAPFA-"b5bded9"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:480) ~[TecnoSpigot-Roleplay.jar:git-YAPFA-"b5bded9"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:442) ~[TecnoSpigot-Roleplay.jar:git-YAPFA-"b5bded9"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1246) ~[TecnoSpigot-Roleplay.jar:git-YAPFA-"b5bded9"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[TecnoSpigot-Roleplay.jar:git-YAPFA-"b5bded9"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.IllegalStateException: Unable to find method null ([class net.minecraft.server.v1_15_R1.ServerConnection]).
	at de.stylextv.gs.packet.Reflections.getTypedMethod(Reflections.java:237) ~[?:?]
	at de.stylextv.gs.packet.Reflections.getMethod(Reflections.java:203) ~[?:?]
	at de.stylextv.gs.packet.Reflections.getTypedMethod(Reflections.java:235) ~[?:?]
	at de.stylextv.gs.packet.TinyProtocol.<clinit>(TinyProtocol.java:37) ~[?:?]
	... 20 more
```

Please fix that.

**Comment by stylextv** [comment]
This is an issue with TinyProtocol on paper spigot servers: https://github.com/dmulloy2/ProtocolLib/issues/788

**Comment by stylextv** [comment]
Fixed in the latest version
